Missiles destruction like ogame
XGProyect/XG-Proyect-v3.x.x pull request #555
Opened 2023-05-13 20:08 UTC by jonamix-ar

Destroy missiles like ogame redesign & and update description ogame ENG and ES

XGP
![image](https://github.com/XGProyect/XG-Proyect-v3.x.x/assets/2124810/8d720754-b000-4e5c-9339-d7ba5ff66ac4)

Redesign
![image](https://github.com/XGProyect/XG-Proyect-v3.x.x/assets/2124810/03403ca4-3a7e-4672-9e78-d41caba458a8)

2023-05-28 14:35 UTC, LucasKovacs requested changes
it needs changes @jonamix-ar

2023-05-28 14:35 UTC, LucasKovacs commented on resources/lang/spanish/game/infos_lang.php
> +        'building_missile_silo' => 'El silo es un lugar de almacenamiento y lanzamiento de misiles planetarios. Por cada nivel de tu silo, tienes espacio para 5 misiles interplanetarios o 10 misiles
el 0 no debería ser %s ?

2023-05-28 14:35 UTC, LucasKovacs commented on app/Models/Game/Infos.php
> +    public function getDestroyMissiles(int $antiballistic, int $interplanetary, int $planet)
por que get si estas haciendo únicamente un update?

2023-05-28 14:35 UTC, LucasKovacs commented on app/Http/Controllers/Game/InfosController.php
> +            // Obtener los valores ingresados en los campos del formulario
ingles para los comentarios

2023-05-28 14:35 UTC, LucasKovacs commented on app/Http/Controllers/Game/InfosController.php
> +            $interplanetaryCapacityPerLevel = 5; // Capacidad de misiles interplanetarios por nivel
para esto no tenemos constantes o una formula? yo creo que si que había

2023-05-28 15:12 UTC, jonamix-ar commented
Lo de la formula tengo que verlo pero me parece que nunca la hicimos, siempre lo tuvimos como mod a esto, segundo voy a rehacer parte del Código por que estoy haciendo la tabla, estuve viendo que es otro controlador como lo usa ogame.

2023-06-04 11:49 UTC, LucasKovacs commented
Era solo el feedback que deje

2023-06-17 18:35 UTC, jonamix-ar commented
Lucas voy a pasar esto a Formulas para reutilizarla en el building y infos


private function getMissilesItemLimit($item_id, $amount_requested)
    {
        // calculate missile amount
        $this->calculateMissilesAmount();

        // start applying formulas
        $silo_size = $this->planet[$this->objects->getObjects(44)] * 10;
        $taken_space = $this->missiles[Defenses::defense_anti_ballistic_missile] + ($this->missiles[Defenses::defense_interplanetary_missile] * 2);
        $max_amount = $silo_size - $taken_space;
        $amount = 0;

        if ($item_id == Defenses::defense_anti_ballistic_missile) {
            $amount = $max_amount;
        }

        if ($item_id == Defenses::defense_interplanetary_missile) {
            $amount = floor($max_amount / 2);
        }

        if ($amount_requested > $amount) {
            $amount_requested = $amount;
        }

        return $amount_requested;
    }

2023-06-17 19:04 UTC, LucasKovacs commented
Avísame y hago nuevo review

2023-06-21 20:47 UTC, closed without merging